dbm-network/mods

README.md
Your Discord name with tag:
Are you already a member of the DBM Mod Guild?
Category of actions you added (Store Things/UI/...):
If you aren't a  member of the Guild, make sure to join! Link is in the README file :kappa:
=> Added small version badge.

README.md, actions/aaa_wrexmods_dependencies_MOD.js, actions/action_list_comment_MOD.js, actions/mod_info_MOD.js, actions/parse_from_stored_json_MOD.js, actions/send_json_to_webapi_MOD.js, actions/set_server_splash.js, actions/set_server_splash_FIX.js, actions/store_json_from_webapi_MOD.js, actions/store_regex_matched_variable_MOD.js, actions/store_server_info_MOD.js, js/WrexMods.js, modinfo.json
Ready for update? Wait until I manged everything.
=> Publish 1.8.1

actions/file_control_MOD.js
=> File Control MOD

actions/weather_MOD.js
The sequence won't stop if it errors anymore.
=> Sequence won't stop if it errors

actions/find_text_MOD.js
=> New mod: Find Text

actions/replace_MOD.js
Update replace_MOD.js (Miss-spelling in a Word.), Next Update: `Convert a Variable MOD`
=> Update replace_MOD.js (Miss-spelling in a Word.)

actions/convertVariable_MOD.js
**__INFO (What it does)__**:
Basically, it Converts your input or Variable into a Number or String.
String is normally those with `""`/`''`/ ` `` `
Numbers are as expected Numbers but without those "" things.
These Numbers will be saved if the input was a word as "NaN" (Not a Number) because the Input weren't a Number (Convert: To Number).
Strings are mostly saved as `"Hello"`. Strings aren't affected by anything so the input will be the same as before, but if it were a Number before, it Convert's into a String. Useful to Convert a saved json from webapi which it was a number before.
More Information  for Strings in  Javascript(Programming language.): ( https://www.w3schools.com/jsref/jsref_obj_string.asp ),
More Information for Numbers(Int) in Javascript(Programming lanquage.): ( …
=> Added "Convert a Variable"

actions/file_control_MOD.js, actions/store_time_info.js
Fixed File Control.
Rewrote File Control.
Cleaned out the gutters.
Commented out a console.log() in Store Time Info (returned spamage of Undefined)
added a Month (Text) Subtitle for dbm
Added a author note to File Control
Thank You Wrex for the continued guidance in JS
=> Fixes, Rewrite & More

actions/file_control_MOD.js
=> Added a dependency for installing mkdirp

actions/file_control_MOD.js
const WrexMODS = _this.getWrexMods(); to const WrexMODS = this.getWrexMods();
=> hmm how did that get in there

actions/aaa_wrexmods_dependencies_MOD.js, actions/store_emoji_info_MOD.js
Added Store Emoji Info mod and added getEmoji to aaa_wrexmods_dependencies_MOD.js
=> Store Emoji Info mod

actions/store_emoji_info_MOD.js
Sorry i forgot to add version number ^^
=> Added version number

actions/edit_emoji_MOD.js
=> Edit Emoji

actions/set_member_voice_channel_perms_MOD.js
This mod serves to set the permissions of a specified member on a specified voice channel
Made by MrGold
=> Set Member Voice Channel Perms

actions/set_role_perms_MOD.js
Now it works as it should be and the "Priority Speaker" option has been added
Made by MrGold & EliteArtz
=> Set Role Permissions

actions/store_voice_channel_info.js
Added: Is VC Full, Guild, Manageable, Parent
=> Added new features

actions/store_message_info.js
Don't forget to delete store_message_info_MOD.js
=> Merged Store Message Things with Store Message Info

actions/get_stats_from_dbxyz_MOD.js
Uploaded by request of author (Ohhlookitsrazorr#4651)
=> Get api info from discordboats.xyz

actions/change_prefix_MOD.js
=> added change prefix back

actions/game_server_MOD.js
You can use this mod for CS:GO, Minecraft servers etc
=> Added Store Game Server Info

actions/set_afk_channel_MOD.js
=> Added Set AFK Channel

actions/store_emoji_info_MOD.js
Created by NetLuis and updated by MrGold
Added "Emoji Timestamp", "Emoji Is Deletable?", "Emoji Has Been Deleted?", "Emoji Server", "Emoji Identifier", "Emoji Is Managed By An External Service?" and "Emoji Requires Colons Surrounding It?"
=> Store Emoji Info updated

actions/delete_emoji.js, actions/find_channel.js, actions/find_emoji.js, actions/find_role.js, actions/find_server.js, actions/find_voice_channel.js
I hope this is the last of them :sweat:
=> Fixed Find deprecated warnings

actions/start_rss_feed_MOD.js, actions/stop_rss_feed_MOD.js
By using an URL that links to and RSS feed/atom you can call the actions after these actions upon the feed update.
=> Start & Stop an RSS Feed.

actions/create_categoryChannel_MOD_EliteArtz.js, actions/create_voice_channel.js
Fixed bugs in "Create Voice Channel" & "Create Category Channel"
=> Fixed some bugs

actions/restart_bot_MOD.js
It restarts your bot
Created by MrGold
Fixed by NetLuis
=> Restart Bot

actions/store_message_info.js
=> Added "Message URL" option

actions/spotify_search_MOD.js
It stores information about Spotify tracks, artists, playlists and albums
Created by MrGold
=> Spotify Search

actions/member_data_list_MOD.js
While using this mod you can grab the members tag from a data-name that are stored in 'players.json'. You can use these members to sort their data/don't sort and/or use a result limit. This mod can be used to make a leader-board without MySQL or any other SQL Database.
=> Added store member data list mod

actions/send_embed_message.js, actions/send_message.js
Added "If Message Delivery Fails" option to Send Message & Send Embed Message
=> Added "If Message Delivery Fails" option to Send Message & Send Embed Message.

actions/check_member_data.js, actions/check_server_data.js
Added "Length is Bigger Than, Length is Smaller Than, Length Equals, Starts With and Ends With" options.
=> Added more options to Check Server & Member Data

actions/convert_variable_MOD.js, actions/find_item_in_list_MOD.js
[Find Item in List] - This action searches for any item you want in a list
[Convert Variable] - The new version of Gold now supports Number(Float), UpperCase and LowerCase conversion too
=> Added Find Item in List & updated Convert Variable

actions/store_category_info_MOD.js
Fixed Variable Storage problem in Editor and cleared up code.
Also it doesn't requires Wrex Mods anymore.
=> Fixed Variable Storage problem

actions/play_youtube_playlist_MOD.js
This action is able to add every video in a youtube playlist to the queue.
=> Added Play YouTube Playlist

actions/find_item_in_list_MOD.js, actions/restart_bot_MOD.js, actions/youtube_search_MOD.js
Fixed [Find Item in List]:
The variable which contains the result choosed the name from the input variable.
Merged [Store YouTube Playlist Info] & [Store YouTube Info] with [YouTube Search]:
The new version of Store YouTube Info is now able to get informations from a playlist too.
Modified [Restart Bot]:
This is a modified version of the Restart Bot mod which now allows you to restart your bot with other file names.
=> Many new stuff and fixes

actions/youtube_search_MOD.js
This action is now able to search for videos again and for playlists too.
=> Fixed YouTube Search

actions/store_twitch_info_MOD.js
This mod will store a specific information from Twitch, you can choose between "Channel", "Stream", "Video" and "Game" Infos.
=> Added Store Twitch Info

actions/find_item_in_list_MOD.js
Fixed the issue with position 0
=> Fixed Find Item in List

actions/store_channel_info.js
=>  Fix for Store Channel Info

actions/create_embed_message.js, actions/set_embed_description.js, actions/set_embed_footer_MOD.js, actions/set_embed_timestamp_MOD.js
I've added two features to the DBM Embeds that have been requested for a long time: Author URL and the ability to customize the timestamp. I've done some UI changes too, to make the actions more clear due the changes that I've made.
- Updated 3 Mods
- Added 1 Mod
=> Embed Actions Update

actions/loop_queue_MOD.js
This action will loop the whole queue or the current playing item.
=> Added Loop Queue

actions/set_time_restriction_MOD.js
=> Cooldown Action MOD

actions/create_embed_message.js
Fixed that little "Cannot read property 'temp' of undefined" TypeError
=> Fix for Create Embed Message

actions/loop_queue_MOD.js, actions/mod_info_MOD.js, actions/store_audio_info_MOD.js
This is required for some operations in the Loop Queue mod if you want to play a local file or webstream.
=> Updated DBM Mods music function

actions/store_twitch_info_MOD.js
There was an issue while checking if a channel is live or not (Didn't store true)
=> Fixed Store Twitch Info

actions/remove_item_from_list.js
Fixed: [TypeError: Cannot read property 'temp' of undefined]
=> Fixed Remove Item from List

actions/create_embed_message.js
There was a mistake which has been caused from the merge of Set Embed Timestamp with Create Embed. Fixed that too! C:
=> Fixed Create Embed

actions/skip_queue.js
Skip Queue is now compatible with the Loop Queue mod.
=> Added Skip Queue

actions/youtube_search_MOD.js
Some users had problems with the last one because it used multible node modules (and some were very slow) to find results. This brand new version includes MANY more options and a better support for playlists.
=> YouTube Search [Remake]

actions/play_youtube_playlist_MOD.js
Updated the node module to support longer playlists.
There are no changes to the UI itself...
=> Updated: Play YouTube Playlist

actions/create_embed_message.js
Added a debug button for users that have problems with the new version of this action.
=> Updated: Create Embed

AlternativeMods/call_command_or_event.js, actions/check_if_member_MOD.js
=> Small fixes

actions/store_server_info.js
=> Updated: Store Server Info

actions/add_embed_field.js, actions/find_emoji.js, actions/find_emoji_in_msg_server_MOD.js, actions/send_embed_message.js, actions/send_gif_MOD.js, actions/send_image_MOD.js, actions/send_log_message_MOD.js, actions/send_message.js, actions/set_embed_description.js
I was told to move this, so here you go. It's basically just a few clarifications to inform people about certain stuff that may not be clear.
=> Clarifications

actions/inspect_list_or_object_MOD.js
This action will try to inspect lists and objects to display it's items.
=> Added Inspect List / Object

actions/filter_list_or_object_MOD.js
This mod allows you to filter lists / objects however you like
=> Added Filter List / Object

actions/check_variable.js
Added a "Matches Full Regex" option to give users access to a much more custom Regex generation type.
=> Updated Check Variable

actions/send_stats_to_dbl_MOD.js
Now, you don't have to install any modules.
=> Send stats to DBL; you don't need the module now.

actions/check_if_member_MOD.js, actions/parse_from_stored_json_MOD.js, actions/read_file_MOD.js, actions/send_image_MOD.js
Added check if member is current server owner
Fix 'store in' not working (send image mod)
Added debug mode, based on Armağan version to Parse from stored JSON.
=> Mod additions + fix to Send Image MOD

actions/check_parameters.js, actions/check_variable.js, actions/mod_info_MOD.js, actions/store_member_info.js
Removed all things that were already in Check if Member.
Added member last message ID
=> Update store mem info | check var, check params | fix action list info // music

actions/run_sql_query_MOD.js
operatorAliases support was removed in v6 from squilize
(Only Removed the operatorAliases from the code the other changes are lines that changed position)
=> Operator Alias Fix

actions/parse_from_stored_json_MOD.js
Fixed misalignment of the variable field, remove store in nothing option.
=> Fix misalignment \ rmv store in nothing

AlternativeMods/game_server_MOD.js
Now, it works with most* of servers
=> New module & Better UI

actions/store_role_info.js
Added: Role Creation Date and Role Permissions (numbers)
=> New options in Store Role Info

actions/store_server_info.js
Added: Server Explicit Content Filter
=> New option in Store Server Info

actions/store_message_info.js
- Message Length
- Message Guild
- Message Attachments Count
- Message Type
- Message Creation Date
- Message Webhook ID
=> New UI, fixes, and options in Store Message Info

actions/send_embed_message.js
Was added the Message Content option
It's that message at the top of your embed, the content
> Preview:
=> Update in Send Embed Message

actions/store_member_info.js
=> Added Custom Status

actions/store_command_info_MOD.js, actions/store_date_info_plus_MOD.js
> See information for some command.
**Including:**
- Command Name
- Command ID
- Command Type
- Command Restricton
- Command User Required Permission
- Command Aliases
- Command Time Restriction
- Command Actions Length
*Idea by A1berti*.
---
> It's a mod that has the same premise as Store Date Info, but much more complete and more practical to use.
In Builder mode you can build your date your way without having to take variable by variable. It may seem confusing, but just look at the example in mod.
You can see the documentation of the module that is used to better understand, I recommend <a href="https://momentjs.com/docs/#/displaying/format/">this part</a>, there it shows all the parameters you can use in "Build It" field.
=> Store Command Info & Store Date Info Plus MOD

actions/find_text_MOD.js
The mod will now read variables in the source text.
I also added an error message in case the text to find isn't found in the source text.
I also changed a few terms.
=> Fixed Find Text MOD

actions/canvas_create_background.js, actions/canvas_create_image.js, actions/canvas_crop_image.js, actions/canvas_draw_image.js, actions/canvas_draw_text.js, actions/canvas_edit_image_border.js, actions/canvas_generate_progress_bar.js, actions/canvas_image_filter.js, actions/canvas_image_options.js, actions/canvas_save_image.js, actions/canvas_send_image.js, actions/clone_channel_MOD.js, actions/convert_text_to_list.js, actions/delete_bulk_messages_MOD.js, actions/delete_member_data_MOD.js, actions/delete_server_data_MOD.js, actions/edit_embed_object_MOD.js, actions/edit_item_from_list_MOD.js, actions/remove_from_queue_MOD.js, actions/shuffle_queue_MOD.js, actions/store_audit_log_info_MOD.js, actions/store_audit_log_list_MOD.js, actions/store_data_list_MOD.js, actions/store_message_info.js
=> Added Option 22

actions/await_response_call_action_MOD.js
- Temporary variables can now be used on the filter
- Added more variables that can be used on the filter
- Added more examples
- Revised the UI
- When the max is set to 1, it only stores a message instead of a collection
- When the max is bigger than 1, it stores a list instead of a collection
=> Revised Await Reaction Call Action

actions/store_server_info.js
Added delay to allow bans and invites to fetch. Previously returned undefined or 0.
fixes: https://github.com/dbm-network/mods/issues/231
=> fix(store_server_info): storing invites and bans work properly

actions/color_from_image.js, actions/color_from_image_MOD.js
=> Added get dominant color mod

actions/store_attachment_info_MOD.js
- Converted action into a class. 
- Fixed #274
=> fix(StoreAttachmentInfo): action not being called

emit_event_MOD.js
This action allows users to emit events using the bot.
=> feat(EmitEvent): created event emitter action

actions/store_message_info.js
Fix option 22 for store message embed object, tested on DBM beta 1.5.9, DBM mod 1.9.7 and discord.js 11.5.1.
This PR change for small issue i found on subtitle array and fix issue for https://github.com/dbm-network/mods/issues/288
=> Resolve issue #288 Message Embed Object

actions/set_time_restriction_MOD.js, actions/store_message_info.js
This pr is about adding feature restrict by server or global. Now member couldn't abuse the command by call the command in server 2 after use the command in server 1.
**Status**
=> added set time restriction feature

README.md, actions/await_response_call_action_MOD.js, actions/run_script.js, actions/set_time_restriction_MOD.js
Changed the UI of the Run Script. Made by @MrG0ld 
**Status**
**Preview**
=> feat(RunScript): added changes made by MrGold

actions/game_server_MOD.js
**Status**
This PR fixes an issue where trying to pull number of online players in a fivem server resulted in undefined.
=> fix(GameServer): amount of players

actions/set_time_restriction_MOD.js, actions/store_message_info.js, actions/store_server_info.js
Fix error about `TypeError: Cannot read property 'size' of undefined`
**Status**
=> fix(Store Server Info)

actions/description_MOD.js, actions/get_command_description_MOD.js
Implements a system for getting/setting command descriptions. This can be useful for making help commands, because a simple command description setter can make it easier to implement new commands, without all of the extra effort of writing extra code.
=> Command Description + Get Command Description

actions/send_message_to_console_MOD.js
Added color support through [chalk](https://www.npmjs.com/package/chalk) (Auto-install through WrexMODS). Also added an Error Message (Non-Fatal) to Empty Logs both in DBM and in Logs. And a UI change which displays the log color in DBM as it would be in the command prompt.
Colors can be very useful for displaying more advanced information: i.e. Better Errors, Warnings, Comments, etc.
**Status**
=> Added colors to send_message_to_console_MOD.js

actions/file_control_MOD.js
New option added called **"Insert"** which appends at a given line.
Uses `npm i insert-line` to append a file at a specific position which previously required a Script.
=> Added Insert at Position to File Control

actions/set_bot_activity_MOD.js
=> Removed bengis

actions/play_youtube.js
Check if msg exists to avoid `TypeError: Cannot read property 'author' of undefined` when used in an event
**Status**
=> Update Play Youtube

actions/canvas_image_options_MOD.js
evalMessage added because Leon forgot it :3 (Fix for somebody in #support but I don't feel like getting destroyed by mods for posting files.)
**Status**
=> Allow usage of variables in canvas_image_options_MOD.js

actions/convert_seconds_to_days_MOD.js, actions/format_seconds.js
Added a bunch of Time Formats and upped efficiency greatly.
**Status**
=> Added Format Seconds

actions/member_data_list_MOD.js
It was a mess, it no longer is, ~50 useless lines removed.
**Status**
=> Cleaned up member_data_list_MOD.js

actions/clone_channel_MOD.js
Now uses the proper clone method.
**Status**
=> Updated and moved clone_channel_MOD.js

actions/store_audit_log_list_MOD.js
Removed `options.after` which is no longer available in v12.
**Status**
=> Updated and moved store_audit_log_list_MOD.js

actions/anchor_jump_MOD.js
Again with new branch
**Status**
=> support anchor jump with run script

actions/check_permissions_MOD.js, actions/compare_permissions_MOD.js, actions/control_permissons_MOD.js, actions/create_permission_MOD.js, actions/set_channel_permissions.js, actions/set_permissions_MOD.js, actions/store_channel_permissions_MOD.js, actions/store_permissions_Info_MOD.js, actions/sync_channel_permissions_MOD.js
=> Add permissions mods

actions/check_role_permissions_MOD.js
v12 compatibility
NOTE: I wasn't sure whether admin should override the permission or not, I went with no, simply add true as second parameter if you do want to have that in.
**Status**
=> moved and updated

actions/store_bot_client_info_MOD.js
Last Message ID - global last message the bot has sent
Are Commands Case Sensitive? - returns a true/false value if case sensitive commands are turned on/off in settings
**Status**
=> Added last msg ID and case sensitive true/false

actions/store_message_params_MOD.js, not_converted/store_message_params_MOD.js
=> Converted Store Message Params

actions/find_reaction_MOD.js
=> Fetch reaction when returning

actions/find_reaction_MOD.js
Fixes https://github.com/dbm-network/mods/issues/306
**Status**
=> Fetch reaction 

actions/check_role_permissions_MOD.js, default_actions/create_voice_channel.js, default_actions/delete_emoji.js, default_actions/find_channel.js, default_actions/find_emoji.js, default_actions/find_role.js, default_actions/find_server.js, default_actions/find_voice_channel.js, default_actions/loop_through_all_servers.js, default_actions/set_member_voice_channel.js, default_actions/store_member_info.js, default_actions/store_message_info.js, default_actions/store_role_info.js, default_actions/store_server_info.js
**Status**
Changes and other info
**Items I DID NOT TEST or MODIFY**
- Run Script
- Store Time Info
- Skip Queue
**Items I DID NOT MODIFY but did test**
- Create embed message
- Edit message
- Get Item From List
- Send Message
- Loop Through List
- Remove Item From List
- Send Embed Message
- Set Embed Description
**Items I modified and tested (as well as changes)**
- Create voice channel 
- Store role info
- Store server info // Remove default channel, change default role
- Store Message Info
- Store Member Info
- Set Member Voice Channel
- Loop through all servers
- Find Voice Channel
- Find Server
- Find Role // Added Find by raw position
- Find channel
- Find Emoji
- Delete Emoji
- Create Voice Channel
=> Converted default actions

actions/edit_message.js
No updates to make.
**Status**
=> Moved + Fixed

actions/create_embed_message.js, actions/edit_message.js, default_actions/create_embed_message.js
Changes: 
- l.215-218, no varName, doing all of that is pointless.
- l.229, the author fields don't care if they are undefined, the extra checking is unnecessary.
- l.265, removed a bunch of pointless spaghetti for a better option (Haven't decided on any default amounts, the `null`s can be replaced)
~~- l.298-323, made `Actions.createEmbed()` more advanced + docs for it.~~
**Status**
=> Updated Create Embed Message and Edit Message

README.md
updated download links to download Alpha mods & how to install DBM Alpha
**Status**
=> docs: updated download links & how to install dbm alpha

actions/await_reaction_call_action_MOD.js, actions/await_response_call_action_MOD.js, actions/check_dbl_voted_MOD.js, actions/check_if_command_exists_MOD.js, actions/check_if_file_exists_MOD.js, actions/check_if_member_MOD.js, actions/check_if_message_MOD.js, actions/check_member_data.js, actions/check_parameters.js, actions/check_role_permissions_MOD.js, actions/check_server_data.js, actions/set_channel_permissions.js, actions/set_time_restriction_MOD.js
=> Update Fix for anchor options

actions/delete_bulk_messages_MOD.js, actions/find_member.js, actions/send_embed_message.js, actions/send_mail_MOD.js, actions/send_message.js
=> Add anchor options

actions/store_json_from_webapi_MOD.js
fixing eslint issues by making more of them 👓
**Status**
=> fixed? eslint issues

actions/store_twitch_info_MOD.js, actions/twitch_authentication_MOD.js
Fix twitch mods by adding authenticate
**Status**
=> Update Twitch Mods

actions/clone_channel_MOD.js
=> v12 update

actions/restart_bot_MOD.js
=> Make Restart Bot close old node process

actions/blocklist_MOD.js
[Recommendation](https://chromium.googlesource.com/chromium/src/+/master/styleguide/inclusive_code.md) by Danno.
**Status**
=> inclusive code

actions/download_file_MOD.js
=> Refactored Download File

actions/store_message_params_MOD.js
Joining no longer uses a RegExp which I'm not sure why it did originally, `+ 1` removed to make it less confusing.
**Status**
=> minor fixes

actions/send_message_to_twitch_chat_MOD.js, docs/mods.json
=> Send Message to Twitch Chat action

actions/cleverbot_MOD.js
I've added cleverbot-free API to use in this mod.
**Status**
=> Adjusting cleverbot-MOD.js

actions/run_sql_query_MOD.js
=> fix: Run SQL Query

actions/run_sql_query_MOD.js
Fixed for query type
**Status**
=> Fix Run SQL Query

actions/run_sql_query_MOD.js
Support lower case in query, Resolve #462
**Status**
=> Updated SQL query

actions/youtube_info_MOD.js
Fixed 403 error from youtube-info by replacing it with yt-sr.
**Status**
=> replace youtube-info with ytsr to fix 403 error

actions/youtube_info_MOD.js
added ytdl-core mixed in with ytsr to provide the best result.
**Status**
Tested for working on video URL and video title.
- [/ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
read above. 
=> Thanks to leonz added bunch more options back

actions/edit_channel_MOD.js
Updated this for monks, allows you to make the channel nsfw/remove channel nsfw
**Status**
=> Added NSFW options to Edit Channel

actions/run_command_in_console_MOD.js
Added the word `result` to make it better, kthxsbye
**Status**
=> Added "result" to Store In to avoid confusion 

actions/delete_bulk_messages_MOD.js, actions/stop_bot_MOD.js
1. Fixed Delete Bulk Message MOD for delete specific amount of messages
2. Update Stop Bot for exit nodejs, before it was just stop the discord.js without exit nodejs
**Status**
=> Fix Delete Bulk Messages MOD and made Stop Bot exit node process

actions/convert_to_world_time_MOD.js, docs/mods.json
**Converts local time to different time by inputting the timezones**
**Status**
=> Convert to world time

actions/play_youtube_playlist_MOD.js
=> Replace simple-youtube-api with ytpl + eslint fix

actions/store_file_info_MOD.js, docs/mods.json
=> Store File Info

docs/mods.json
add descriptions to all mods
**Status**
=> Added descriptions to all mods

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Added a check box to the Status section, indicating whether documentation was added, if necessary.
This PR will close #497.
**Status**
=> chore: Add Documentation Field to PR Template

actions/store_youtube_channel_info_MOD.js
=> fix(StoreYoutubeChannelInfo): invalid option

actions/youtube_search_MOD.js
No video existing previously caused a fatal error, deciding what happens should be left to the user.
**Status**
=> fix(mods): no video fatal error

convert_to_base64_MOD.js, docs/mods.json
=> Convert to Base64

actions/store_regex_matched_variable_MOD.js
[Build Regex](http://buildregex.com) now unavailable, replaced with [RegExr](regexr.com).
**Status**
=> chore(mods): update RegEx builder website

actions/store_game_info_MOD.js
V12 Compatibility. (`game` => `activities[0]`)
Removed all the if statements that were unnecessary and set the result to `'null'`.
More option groups.
Changed default game.
**Status**
=> refactor(mods): store game info

actions/check_global_data_MOD.js, actions/check_member_data.js, actions/check_server_data.js, actions/control_global_data_MOD.js, actions/delete_global_data_MOD.js, actions/delete_member_data_MOD.js, actions/delete_server_data_MOD.js, actions/store_global_data_MOD.js, docs/mods.json
The section of the data related actions will be changed on the default actions, so this will be merged when the update goes live as well
**Status**
=> refactor(data): switched all data actions to Data instead of Deprecated

actions/control_server_prefix_MOD.js
Fix data.permissions error
**Status**
=> Fix Control Server Prefix 

extensions/server_prefixes/server_prefixes_EXT.js
Fix server id error, fix custom data error, completely rewrite loadPrefixes for read-ability / simplicity, remove debug mode
**Status**
=> Fix Server Prefixes

extensions/dbm_dashboard/dashboard_EXT.js, extensions/dbm_dashboard/dashboard_EXT/actions/routes/adminPanel/adminPanel_route.js, extensions/dbm_dashboard/dashboard_EXT/actions/routes/dashboard/dashboard_route.js, extensions/dbm_dashboard/dashboard_EXT/actions/routes/dashboardPanel/dashboardPanel_route.js, extensions/dbm_dashboard/dashboard_EXT/actions/routes/home_page/home_route.js, extensions/dbm_dashboard/dashboard_EXT/actions/routes/profile/profile_route.js, extensions/server_prefixes/server_prefixes_EXT.js
- Fixed an issue with DBM updating the config file to an old version.
- Added perm authentication to the guild routes.
- Updated the README.MD
- Fixed an issue with settings not being defined.
- Closes #513 
**Status**
=> Panel Update / Fixes

docs/events.json, events/invite_used_EVT.js, events/member_move_voice_channel_EVT.js, events/on_audio_end_EVT.js, events/on_audio_pause_EVT.js, events/on_audio_resume_EVT.js, events/on_audio_start_EVT.js, events/on_audio_volume_change_EVT.js
Compared never-identical objects, so the if would always return true.
**Status**
When an invite is used, call the event with invite code and guild to facilitate creation of invite managers.
**Status**
Implemented `for...of` style for audio events, moved minor things.
**Status**
Documentation added to most events.
**Status**
=> new(events): added invite used, fixed moved VC, docs

events/invite_used_EVT.js
=> fix(events): bot not starting.

README.md
Changes title from **DBM Network** to **DBM Mods**
**Status**
=> readme: href title

actions/get_lyrics_MOD.js
Removed un-used template literals, changed datatype names to standard.
**Status**
=> style(mods): useless template literals, datatypes

events/member_move_voice_channel_EVT.js
Conditions were incorrect, `channel` property may still be populated, check for existing ID?
Channel ID has to be different for it to be a move.
**Status**
=> fix(events): move member vc conditions

actions/download_file_MOD.js
Added callNextAction which was missing.
**Status**
=> fix(actions): download file call next action

actions/file_control_MOD.js
The old pull request had to be closed due an error popped by the repository. Added the visibility factor.
**Status**
=> Enhancing File Control

actions/set_slowmode_MOD.js
Fixed a fatal bug that would cause no actions to occur after the slow mode action.
**Status**
=> Fixed fatal flaw

events/on_member_role_add_EVT.js, events/on_member_role_removed_EVT.js
=> fix: on member role add/remove triggering when roles weren't updated

actions/add_item_to_list.js, actions/edit_item_from_list_MOD.js
Fixed the action by adding the cache parameter in the evalMessage function.
Added a small footnote on the top to provide DBM Users information on how positioning works with Lists.
**Status**
=> Fix for Add/Edit Item to List

actions/youtube_search_MOD.js
Fixed YouTube Search so it works again.
Make sure you have the latest ytsr `npm i ytsr@latest`
Also, make sure you have the latest ytdl-core `npm i ytdl-core@latest`
**Status**
=> Fix YouTube Search

actions/member_data_list_MOD.js, actions/store_data_list_MOD.js
The new [major version of `fast-sort`](https://github.com/snovakovic/fast-sort/blob/master/CHANGELOG.md#300---2021-04-08) has removed their default export in favor of named exports 
**Status**
=> fix(*_data_list): fastsort is not a function

actions/store_youtube_channel_info_MOD.js, actions/youtube_info_MOD.js, actions/youtube_search_MOD.js
It Fixes YouTube Mods, duh.
**Status**
=> Update/Fix All YouTube Mods

actions/check_variable.js
=> Fix Falsey variables

actions/math_operation_MOD.js
=> Move text to the left *shrug*

actions/spotify_search_MOD.js
**This goddamn thing already worked. You all are too stupid to install a module for yourselves -_-**
**Status**
=> Add Auto Module Installer, Add error w/o creds

docs/mods.json
=> Forgot to add new section info to docs my bad

actions/split_MOD.js, actions/store_json_from_webapi_MOD.js
Change all console printing to debug mode.
Makes split mode not error out, continue actions.
**Status**
=> Console Print Changes

actions/send_message_to_console_MOD.js
Guess doing it that way doesn't work. Okay.
**Status**
=> Fix Send Message to Console

events/invite_used_EVT.js
Added permission check to Invite Used, fixed spamming console with missing permission. 
**Status**
=> Added permission check to Invite Used

.eslintrc.yml
=> Added more globals

events/cron_scheduler_EVT.js, events/delete_bulk_messages_EVT.js, events/member_boosted_server_EVT.js, events/member_join_voice_channel_EVT.js, events/member_leave_voice_channel_EVT.js, events/member_move_voice_channel_EVT.js, events/member_start_streaming_EVT.js, events/member_stop_streaming_EVT.js, events/message_reaction_added_EVT.js, events/message_reaction_removed_EVT.js, events/on_audio_end_EVT.js, events/on_audio_pause_EVT.js, events/on_audio_resume_EVT.js, events/on_audio_start_EVT.js, events/on_audio_volume_change_EVT.js, events/on_member_nickname_changed_EVT.js, events/on_member_role_add_EVT.js, events/on_member_role_removed_EVT.js, events/on_topgg_vote_EVT.js, events/user_update_EVT.js
Scheduler Event: Remove Server Loop & Code Cleanup Scheduled Event
Other Events: Code Cleanup & Reformatting
Added displayName to all 'MOD' Events
**Status**
=> Events Revamp

actions/play_youtube.js
Fix calling next action twice
**Status**
=> Fix calling next action twice

actions/file_control_MOD.js
Changed from plain fs to fs-extra for extended usage (Get rids of dannos in-house dir maker)
Adds a copy file option
**Status**
=> Change to fs-extra && Add Copy

events/invite_used_EVT.js
This should fix the invite used thing not being there at all.
(Happy now Almeida?)
**Status**
=> Fixed used being undefined sometimes, don't fire

actions/member_data_list_MOD.js
Fix that sorting wasn't working at all.
**Status**
=> Fix Sorting

actions/store_html_from_webpage_MOD.js
Request has been deprecated for over a year.
Also removed the "URL Checker" thing, didn't work, seemed useless.
Also removed instructions.
**Status**
=> Finally switch from request to node-fetch

.eslintrc.yml, actions/await_reaction_call_action_MOD.js, actions/await_response_call_action_MOD.js, actions/canvas_create_background_MOD.js, actions/delete_bulk_messages_MOD.js, actions/parse_from_stored_json_MOD.js, actions/store_data_list_MOD.js, actions/store_json_from_webapi_MOD.js
=> Lots of mods use eval, turn the rule off.

actions/aaa_dbmmods_dependencies_MOD.js
Removes all unused methods that were not present in any mod files.
Mostly request and one channel object thing.
**Status**
=> Remove unused methods

actions/send_json_to_webapi_MOD.js
Seems to work as it should, test post JSON website returns a success message.
**Status**
=> Change from reques to node-fetch & debug mode change

actions/find_member.js
title... just added round class to box.
**Status**
- [X This PR changes DBM's interface (methods or parameters added to default methods)
=> Change to fetch non cached user & html updates

actions/youtube_search_MOD.js
Minor code updates, continue instead of breaking.
**Status**
=> Minor code updates

actions/youtube_search_MOD.js
Possible breaking changes, some things had to be removed from changing from ytsr to youtubei (Uses youtube API rather than scraping. Should work better.)
**Status**
=> Changed module used on Youtube Search

actions/store_user_info_MOD.js, docs/mods.json
Store Member Info does not work right with users, so I made a user info mod.
**Status**
=> Added Store User Info

actions/store_user_info_MOD.js
Minor change to the mod before everyone downloads it and I can't change this.
**Status**
=> Move user from info to return statement

actions/send_embed_message.js, actions/send_message.js
This changes issue Failed trigger whatever the reason for fail was.
It closes #629 
**Status**
=> Fix behaviour of 'If Message Delivery Fails'

actions/file_control_MOD.js
Fix all the mistakes in file control with changing it to fs-extra
**Status**
=> Update File Control

actions/game_server_MOD.js
Removes the top embed that was broken.
**Status**
=> Remove the top embed that was broken

actions/convert_variable_MOD.js
It adds the options not parsing the Number, but actually converting to Number (Int/Float)
**Status**
=> Add options for strict conversion in Convert Variable

actions/repeat_string_MOD.js, actions/replace_text_MOD.js
This change removes the use of modules that are not needed
**Status**
=> Get rid of trivial modules

actions/await_reaction_call_action_MOD.js
I believe this will fix it erroring in events from not having message from the cache.
This will solve #729 
**Status**
- [] This PR changes DBM's interface (methods or parameters added to default methods)
- [] This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> Fix Await Reaction not working in events

actions/await_response_call_action_MOD.js
=> minor code change

actions/find_message_MOD.js
Added a check for missing input rather than erroring out from discord API.
**Status**
=> Missing check for search input in Find Message

actions/youtube_search_MOD.js
convert to async, fix calling next action too much
**Status**
=> convert to async, fix calling next action too much

actions/clone_channel_MOD.js
Discord.js `GuildChannel#clone` doesn't accept position.
Delete some duplicates
**Status**
=> Fix/Refactor Clone Channel action

actions/send_message_to_console_MOD.js, actions/set_bot_activity_MOD.js, actions/weather_MOD.js
Refactor the code
Fix calling next action multiple times
**Status**
=> Fix Actions calling next action multiple times

actions/set_member_voice_channel_perms_MOD.js
Fixes issues being found in the guild.
**Status**
=> Set Member Voice Channel: Fix calling next action too much

package-lock.json, package.json
Title.
PR Mayhem
#754 is needed by #753 and #753 is needed by #751
**Status**
=> Update package.json and package-lock.json for linter on PR

typings/globals.d.ts
=> Quick update to globals

actions/create_category_MOD.js
Fixed create_category_MOD.js so I would work with DBM V2
=> fix for dbm V2

extensions/server_prefixes/server_prefixes_EXT.js
Change needed to work on version 2.0
=> server_prefixes_EXT.js (change to DBM 2.0 )

events/invite_used_EVT.js
> A small fix for the event `Invite Used`, updating the syntax to the new DJS Permission Handler.
=> Fix permissions handler

actions/check_dbl_voted_MOD.js
The package is not called @top.gg/sdk but @top-gg/sdk
=> Fixed Top.gg dependencies

actions/set_member_voice_channel_perms_MOD.js, actions/set_role_voice_channel_perms_MOD.js, actions/set_voice_channel_permissions_MOD.js
=> fixed a lot of the issues with voice channel perms

actions/check_if_member_MOD.js
Added timeout check to check_if_member_MOD.js
**Status**
=> Added timeout check to check_if_member_MOD.js

actions/find_category_MOD.js
=> Fix for find_category_MOD.js

actions/send_stats_to_botlist.me_MOD.js, docs/mods.json
Adds an action to easily send statistics to https://botlist.me
**Status**
=> Add send stats to botlist.me

actions/send_embed_to_webhook_MOD.js
=> Fix send embed to webhook action

sharder/sharded-bot.js
Updated the sharder, duh.
**Status**
=> Update sharder with try...catch and new DiscordJS

actions/store_invite_info_MOD.js
=> Fix store invite info MOD

actions/set_role_perms_MOD.js
=> Fix set role permissions MOD

actions/restart_bot_MOD.js
Fixes #769 so console "works" after bot restart.
**Status**
=> Send child process output to console

actions/send_stats_to_botlist.me_MOD.js
=> Fix send_stats_to_botlist.me_MOD.js

events/invite_used_EVT.js
Fixes: DeprecationWarning: Guild#me is deprecated. Use Guild#members#me instead.
**Status**
=> Change guild.me to guild.members.me

actions/check_if_member_MOD.js, actions/store_file_info_MOD.js
One user was having issue with check if member, and it seems like DBM crashes if the member was not found with the new getMemberFromData function, so added a try...catch to the mod.
One person wanted file length and I am unsure why that was not already inside store file info mod, easy addition to the mod.
**Status**
=> Add try_catch to check if member & add file length to file info

actions/spreadsheet_MOD.js, docs/mods.json
Added Spreadsheet Mod
Merging this PR will allow Discord bots to read CSV files, providing a lightweight and efficient way to access static datasets. Furthermore, working with CSV files is often easier for new users than using SQL, making it more accessible for users who are not familiar with complex database systems.
**Status**
=> New Spreadsheet Mod

actions/spreadsheet_MOD.js, docs/mods.json
Added Spreadsheet and Docs Tab to Spreadsheet Mod
This Change is to prevent Confusion and makes it easier to understand it and also how to use this action
**Status**
=> Improvement for Spreadsheet Mod

actions/spreadsheet_MOD.js, actions/transcript_MOD.js, docs/mods.json
Requires  #952 approval before mod can be added.
This PR adds the Transcript_MOD, this allows Users to make a Transcript from a Channel that looks like this : 
The Transcript Mods outputs it as a String that can used to save it in a file or use in other ways
also a example command : https://pastebin.com/QzV6hb6J
Known Problem it needs to use discord-html-transcripts@2.6.1, but I don't know how to force installing this version and not the latest
**Status**
=> Transcript_MOD

actions/store_queue_info_MOD.js
=> Fix store variable not showing up (Store Queue Info)

actions/aaa_dbmmods_dependencies_MOD.js
=> Move require inside try...catch to stop crashing

actions/aaa_dbmmods_dependencies_MOD.js, actions/play_music_MOD.js, actions/store_queue_info_MOD.js
Better wording, and updated action html.
Instead of throwing an error for something that is more or likely not an error, just tell people to restart the bot without the error message.
**Status**
=> Update dbmmods dependencies, again.

actions/control_music_MOD.js
Allows users to change the volume of the music playing
**Status**
- [] This PR changes DBM's interface (methods or parameters added to default methods)
- [] This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> Add volume control to control_music_MOD

actions/check_if_emoji_exists_MOD.js, actions/find_emoji_in_msg_server_MOD.js, docs/mods.json
Updated an action and added a new action to check if an emoji exists or not.
**Status**
=> Update Find Custom Emoji (/stickers) & Add check if emoji exists

actions/control_music_MOD.js
Fixes bot crashes on some features.
**Status**
=> add try...catch to control music

actions/transcript_MOD.js
=> Updated Transcript_MOD

actions/store_queue_info_MOD.js, actions/store_track_info_MOD.js, docs/mods.json
Easier way to store queue info and track information.
**Status**
=> Add features to store_queue_info, add store_track_info and update mods.json

actions/set_slowmode_MOD.js
Fixes the horrible HTML that was in this mod.
**Status**
=> Fix slowmode mod HTML

actions/convert_text_to_list_MOD.js
I don't know, it is fixed tho idk how long it has been broken.
**Status**
=> Fix convert text to list mod

package.json, sharder/sharded-bot.js
Sharded bot was never updated for new discord.js version
**Status**
=> Fix sharded-bot.js

actions/control_music_MOD.js
Fixes mistakes from yesterday
**Status**
=> Fix control_music, don't worry about it.

actions/store_track_info_MOD.js
Allow getting music title information from play music action itself.
**Status**
=> Check if track is track.tracks

actions/store_invite_info_MOD.js
=> Fix store_invite_info.js

.gitignore, actions/run_script_too_MOD.js, actions/store_reaction_info_MOD.js
=> Update run script

actions/store_message_info_MOD.js
- Added store message info as a mod
- Fix unescaped switch statements in original action
- Add message references/replies support
**Status**
=> Store Message Info Improvements

actions/add_commas_to_number_MOD.js, actions/convert_iso_to_timestamp_MOD.js
My first contribution to the DBM mods. You can convert iso8061 dates to unix timestamps with this 👍
=> Convert ISO8061 to Unix Timestamp

actions/youtube_info_MOD.js
=> Fix youtube_info_MOD.js

actions/store_audit_log_info_MOD.js
=> Fix store_audit_log_info_MOD.js

actions/play_music_MOD.js
=> Fix play_music_MOD.js

events/invite_used_EVT.js
=> Fix invite used event

actions/upload_image_to_imgur.js
=> Update upload_image_to_imgur.js to use getMods()
