- actions/store_message_params_MOD.js
fixed RegExp separator being instantiated to join, causing some really weird joining.
**Status**
> fix: RegExp separator

- actions/store_json_from_webapi_MOD.js
Adds a `select` field for whether or not previously stored data in command should be re-used, enabled by default.
Request: `#8qqusy`
**Status**
> feat: previously stored json re-use is not forced

- actions/edit_embed_object_MOD.js
Documentation can be seen [here](https://discord.js.org/#/docs/main/stable/class/MessageEmbed?scrollTo=attachFiles). 
Reported in the [Discord](https://discordapp.com/channels/374961173524643843/728008557190184971/745203037697605692).
**Status**
> fix(mods): attach file to embed, V12 compatibility

- actions/store_attachment_info_MOD.js
- events/message_reaction_added_EVT.js
- events/message_reaction_removed_EVT.js
Fixed the EVT files from destroying the bot process when the reaction event is booted and the reaction originated in a Direct Message between the Bot and the User.
Also fixed grammar fixes to the Store Attachment Info.
**Status**
> fix: event destroying the bot process and subtitles for Store Attachment Info

- events/message_reaction_added_EVT.js
- events/message_reaction_removed_EVT.js
Re-fix to #548. No longer stops, rather checks for existence of server and only then checks for the guild user.
**Status**
> fix(events): DM reactions

- actions/check_if_member_MOD.js
- It enables `Is Speaking?` option
- It returns Boolean value for options that are expected to return Boolean
**Status**
> Enable Is Speaking? option in Check if member action

- actions/check_if_member_MOD.js
`Is Bot Owner?` option now checks if the member is one of the multiple owners
**Status**
> Support Multiple Bot Owners extension in Check If Member

- actions/send_json_to_webapi_MOD.js
With previous version of code, it called JSON.stringify() on already JSON formed-string. This PR fixes this unintended behaviour.
**Status**
> Fix JSON decoding in Send JSON to WebAPI 

- actions/store_attachment_info_MOD.js
Store Attachments Info errors 'message.attachments.array is not a function'. So i fixed it :/
> Fix for Store Attachments Info mod [DBM v2]

- actions/set_role_perms_MOD.js
discordjs v13 no longer awaits ints as permission numbers, but bigints.
**Status**
> Compability with discordjs v13 set role permissions

- actions/store_youtube_channel_info_MOD.js
You are supposed to pass Object instead of String.
**Status**
> Fix Store YouTube Channel Info

- actions/create_webhook_MOD.js
Stops bot crashing if webhook can not be created in channel. Amended if statement from using && to ||.
**Status**
> Stop crashing if webhook can not be created in channel

- actions/set_member_voice_channel_perms_MOD.js
Without the Fix the set_member_voice_channel_perms_MOD doesn't work
**Status**
> Fix set_member_voice_channel_perms_MOD.js

- actions/set_time_restriction_MOD.js
This fixes a long time issue with the mod that it was not working whenever the bot restarted, and by converting the loading functions to async it solves this issue.
Fixes #922 
**Status**
> Convert time restriction to async to make it work on bot restarts

- actions/store_reaction_info_MOD.js
Allow users to get emoji object from reaction info rather than only the name.
**Status**
> Add emoji object to store reaction info

- actions/store_twitch_info_MOD.js
The action store twitch info was previously not able to be saved on smaller displays without editing the action, as it had a scroll bar that didnt work, I have now added a working scroll bar so the action can now be saved on smaller displays without editing the action.
**Status**
- [➖ ] Code changes have been tested against the Discord API and the discord.js wrapper, or there are no code changes
- [➖ ] Documentation has been added/modified, or there is nothing to change (docs/mods.json)
(Nothing API related changed within this PR)
- [❌ ] This PR changes DBM's interface (methods or parameters added to default methods)
- [❌ ] This PR **only** includes non-code changes, like …
> Fix store twitch info on smaller displays

- actions/aaa_dbmmods_dependencies_MOD.js
This allows installing a specific version of a node module for example if something like discord-html-transcripts requires 2.6.1 for v13 of discord.js ;)
Also updated the error message as the module installs even though it still errors out, unsure why that happens, but its not new.
**Status**
> Update Mods Module Installer to allow specific version

- actions/store_embed_info_MOD.js
Closes  #981, incorrectly changed from needing an embed object to message object. Changing source-message to retrieve-from-variable.
**Status**
> Action needs embed object not a message variable

- actions/find_item_in_list_MOD.js
Should have been retrieve-from-variable but changing it back to what it was originally.. i'm not actually sure this matters but only shows lists in dropdown menu.
This unbreaks breaking changes, making new breaking changes, but people don't download mods very often.
**Status**
> Revert change from data.lists to store-in-variable

- actions/set_time_restriction_MOD.js
Time restriction mod will now work on every single command type, and also has a new added option for using days instead of hours. Also added the option to save the time left in nothing to make it look cleaner when you don't want to use that.
In the future it may even be possible to add events to it, or buttons/etc, but I didn't want to test that.
**Status**
> Make set time restiction work with every command type

- actions/game_server_MOD.js
> Fix For 'GameDig' - Store Game Info Mod

- actions/canvas_create_primitive_MOD.js
- actions/seperator_MOD.js
Updates:
- Corrected version numbers.
- Included accurate GitHub links.
- Applied lint for code consistency.
Changes:
- added the Seperator action mod, which is a variant of comment action.
- Introduced canvas create primitive shape.
**Status**
> Updated these

- actions/add_item_to_object_MOD.js
- actions/add_items_to_object_MOD.js
- actions/create_object_MOD.js
- actions/get_item_from_object_MOD.js
- docs/mods.json
These actions allow working with JSON Objects easily.
**Status**
**--> Please feel free to propose name change suggestions for the actions because I'm not so sure about them.**
> add Object actions
